/* VTM V5 status strip. Usage: VTMStatus(STATUS) after a <div id="vtm"></div> mount. */
(function(){
var CSS="\n:root{--blood:#A32D2D;--brass:#854F0B}\n@media (prefers-color-scheme:dark){:root{--blood:#E24B4A;--brass:#EF9F27}}\n.cz{font-family:'Castoro Titling','Cinzel',serif;font-weight:400!important}\n.strip .cz{text-shadow:0 0 4px rgba(255,255,255,.28),0 0 12px rgba(255,255,255,.12)}\n.strip .sw{background:transparent!important;border:none!important;box-shadow:none!important}\n.strip{color-scheme:dark;--surface-0:#0b0909;--surface-1:#1a1517;--surface-2:#0f0c0d;--surface-3:#221c1e;--text-primary:#ebe5da;--text-secondary:#b3a796;--text-muted:#857a6e;--border:rgba(235,229,218,.14);--border-strong:rgba(235,229,218,.28);--fill-control:#2a2325;--bg-danger:#4a1414;--text-danger:#f09595;--border-danger:#a32d2d;--bg-accent:#14304d;--text-accent:#9cc6f0;--border-accent:#378add;--bg-warning:#4a3208;--text-warning:#f2c14e;--bg-success:#173404;--text-success:#97c459;--vtm-blood:#e24b4a;--vtm-brass:#d9a441;color:var(--text-primary);--blood:#E24B4A;--brass:#EF9F27;background-color:#0f0c0d!important;background-image:radial-gradient(ellipse at 50% 135%,rgba(142,27,27,.32),transparent 62%)!important;border-color:#2a1c1e!important;border:0.5px solid var(--border);border-radius:12px;padding:12px 16px;display:flex;flex-wrap:wrap;align-items:center;gap:14px 22px}\n.stat{display:flex;align-items:center;gap:8px;border-radius:var(--radius);padding:2px 4px}\n.lbl{font-family:'Alegreya',Georgia,serif;font-size:15px;color:var(--text-secondary)}\n.boxes{display:inline-flex;gap:3px}\n.bx{width:12px;height:12px;border:1px solid var(--text-muted);display:inline-flex;align-items:center;justify-content:center;font-size:10px;line-height:1;color:var(--blood);font-family:var(--font-sans)}\n.bx.agg{background:var(--blood);border-color:var(--blood);color:var(--surface-2)}\n.bx.hum{background:var(--brass);border-color:var(--brass)}\n.sw{display:flex;align-items:center;gap:10px;margin-left:auto;cursor:pointer;background:none;border:none;padding:4px 0}\n.track{width:44px;height:24px;border-radius:12px;background:var(--fill-control);position:relative;transition:background .25s}\n.knob{position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:var(--surface-2);border:0.5px solid var(--border-strong);transition:transform .25s}\n.sw.on .track{background:var(--blood)}.sw.on .knob{transform:translateX(20px)}\n.changed{animation:flash 1.6s ease-out 2}\n@keyframes flash{0%{background:var(--bg-danger)}100%{background:transparent}}\n@keyframes fill{0%{transform:translateY(-20px) scale(.6);opacity:0}60%{transform:translateY(2px) scale(1.2);opacity:1}100%{transform:none}}\n.note{font-size:13px;color:var(--text-secondary);margin-top:8px;display:flex;align-items:center;gap:6px}\n.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}\n";
var HTML="<h2 class=\"sr-only\">Anika's current status: Hunger, Willpower, Health, and Humanity, with a dice mode switch.</h2>\n<div style=\"padding:1rem 0\">\n<div class=\"strip\">\n<div class=\"stat\"><span class=\"cz\" style=\"font-size:16px;font-weight:600\">Anika</span><span class=\"lbl\" style=\"font-style:italic\" id=\"scene\"></span></div>\n<div class=\"stat\" id=\"st-hunger\"><span class=\"lbl\">Hunger</span><span id=\"meter\" style=\"display:inline-flex;gap:3px\"></span></div>\n<div class=\"stat\" id=\"st-wp\"><span class=\"lbl\">Willpower</span><span class=\"boxes\" id=\"wp\"></span></div>\n<div class=\"stat\" id=\"st-hp\"><span class=\"lbl\">Health</span><span class=\"boxes\" id=\"hp\"></span></div>\n<div class=\"stat\" id=\"st-hum\"><span class=\"lbl\">Humanity</span><span class=\"boxes\" id=\"hum\"></span></div>\n<button class=\"sw\" id=\"sw\" role=\"switch\" aria-label=\"Dice mode\"><span class=\"cz\" style=\"font-size:13px;color:var(--text-secondary)\" id=\"swl\"></span><span class=\"track\"><span class=\"knob\"></span></span></button>\n</div>\n<div class=\"note\" id=\"note\"></div>\n</div>";
window.VTMStatus=function(STATUS,mount){
mount=mount||document.getElementById('vtm')||document.body;
var st=document.createElement('style');st.textContent=CSS;document.head.appendChild(st);var lk=document.createElement('link');lk.rel='stylesheet';lk.href='https://fonts.googleapis.com/css2?family=Castoro+Titling&family=Alegreya:ital,wght@0,400;0,500;1,400&display=swap';document.head.appendChild(lk);
mount.innerHTML=HTML;

const $=id=>document.getElementById(id);const NS='http://www.w3.org/2000/svg';
const DROP='M12 1C12 1 2 14 2 21a10 10 0 0 0 20 0C22 14 12 1 12 1Z';
$('scene').textContent=STATUS.scene;
const from=STATUS.change.trait==='hunger'&&STATUS.hungerFrom!==undefined?STATUS.hungerFrom:STATUS.hunger;
for(let i=0;i<5;i++){const s=document.createElementNS(NS,'svg');s.setAttribute('viewBox','0 0 24 32');s.setAttribute('width','13');s.setAttribute('height','17');s.innerHTML='<path d="'+DROP+'" fill="'+(i<STATUS.hunger?'var(--blood)':'none')+'" stroke="var(--blood)" stroke-width="2"/>';if(i>=from&&i<STATUS.hunger)s.style.animation='fill .6s cubic-bezier(.2,1.4,.4,1) '+(.3+(i-from)*.2)+'s both';$('meter').appendChild(s);}
function track(id,max,sup,agg){const el=$(id);for(let i=0;i<max;i++){const b=document.createElement('span');b.className='bx';if(i<agg){b.classList.add('agg');b.textContent='×';}else if(i<agg+sup){b.textContent='/';}el.appendChild(b);}}
track('wp',STATUS.wpMax,STATUS.wpSup,STATUS.wpAgg);track('hp',STATUS.hpMax,STATUS.hpSup,STATUS.hpAgg);
const hum=$('hum');for(let i=0;i<10;i++){const b=document.createElement('span');b.className='bx';if(i<STATUS.humanity)b.classList.add('hum');else if(i>=10-STATUS.stains)b.textContent='/';hum.appendChild(b);}
const map={hunger:'st-hunger',wp:'st-wp',hp:'st-hp',hum:'st-hum'};if(map[STATUS.change.trait])$(map[STATUS.change.trait]).classList.add('changed');
let on=STATUS.dice;
function noteText(){const n=STATUS.change.note;const base=on?'':'Stats are frozen while dice mode is off.';return (n?n+(base?' ':''):'')+base;}
function paint(){const sw=$('sw');sw.classList.toggle('on',on);sw.setAttribute('aria-checked',String(on));$('swl').textContent=on?'Dice mode on':'Dice mode off';const t=noteText();$('note').innerHTML=t?'<i class="ti '+(on?'ti-droplet':'ti-snowflake')+'" aria-hidden="true" style="font-size:14px"></i><span></span>':'';if(t)$('note').querySelector('span').textContent=t;}
paint();
$('sw').onclick=()=>{on=!on;paint();sendPrompt(on?'[Dice mode ON] Please call for rolls at key moments again.':'[Dice mode OFF] Please resolve checks narratively from here.');};

};
})();
